name: setup-environment
description: Create Python venv and install dependencies

inputs:
  venv:
    description: Python virtual environment path
    required: true
  install:
    description: Indicates whether to install project dependencies
    required: false
    default: 'true'

runs:
  using: "composite"
  steps:
    - id: setup
      shell: bash
      run: |
        rm -rf "$VENV"
        case $VENV in
          *py311*)
            sudo apt install -y python3.11 python3.11-venv
            python3.11 -m venv "$VENV"
            ;;
          *py312*)
            sudo apt install -y python3.12 python3.12-venv
            python3.12 -m venv "$VENV"
            ;;
          *)
            echo "$VENV is not supported"
            exit 1
            ;;
        esac
        source "$VENV/bin/activate"
        python3 --version
        if [ "$INSTALL" = "true" ]; then \
          python3 -m pip install --quiet -r requirements.txt \
        fi
      env:
        VENV: ${{ inputs.venv }}
        INSTALL: ${{ inputs.install }}
